### ISSUE TITLE
VersionInfo class is not created

### ISSUE THREAD

**Issue by PhilippPaetzold** [notpeelz/VersionInfoGenerator#1]
Hello,

I can not access ```VersionInfo``` class, because it is not packed into the assembly. I checked this with ILSpy. The compile time version info from <InformationalVersion> however is properly included and visible when I checked the properties of the DLL.
This is the test project and configuration that I used:

```VersionInfoGeneratorTest.csproj```
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <InformationalVersion>@@GitTag@@-@@GitRevShort@@-@@GitBranch@@</InformationalVersion>
    <VersionInfoClassNamespaceGlobal>true</VersionInfoClassNamespaceGlobal>
    <VersionInfoClassModifiers>internal static</VersionInfoClassModifiers>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="VersionInfoGenerator" Version="2.0.2" PrivateAssets="all" />
  </ItemGroup>
</Project>
```

```AccessVersionInfo.cs```
```csharp
namespace VersionInfoGeneratorTest
{
    public class AccessVersionInfo
    {
        public AccessVersionInfo ()
        {
            //?! there is no class named VersionInfo...
           VersionInfo.
        }
    }
}
```
Do you know whats the issue here?

Best regards
Philipp

**Comment by notpeelz** [comment]
Hey there!

Seems to work for me with the provided csproj:

![image](https://user-images.githubusercontent.com/920910/122400060-5c1e8b80-cf49-11eb-9aa2-603d4f9d1a20.png)
![image](https://user-images.githubusercontent.com/920910/122399847-27aacf80-cf49-11eb-9774-d28199837747.png)

What IDE and OS do you use? Source Generator support was introduced in some Visual Studio 2019 update. Not sure when Jetbrains Rider added support for it. Older versions won't be able to see the generated class.

If you're on the latest version of Visual Studio 2019, try this:
- Clean the solution/project
- Restart Visual Studio
- Rebuild the solution/project and see if the class shows up
- If nothing works, try building from the command line using the [dotnet runtime](https://dotnet.microsoft.com/download): `dotnet build`

**Comment by PhilippPaetzold** [comment]
>What IDE and OS do you use? Source Generator support was introduced in some Visual Studio 2019 update. Not sure when Jetbrains Rider added support for it. Older versions won't be able to see the generated class.

My bad. I installed the latest VS2019 update and it works. Thank you for your fast help!

**Comment by notpeelz** [comment]
Happy to help! I'll add it to the README because I'm sure other people will encounter this issue.
