### ISSUE TITLE
@@CommitsAfterTag@@ variable to count the number of commits on top of a tag

### ISSUE THREAD

**Issue by PhilippPaetzold** [notpeelz/VersionInfoGenerator#2]
Hi again :),

it would be great, if there was an additional variable available in the .csproj and a field in the generated VersionInfo class that stores the number of commits on top of a git-tag. When using ```git describe``` for example I get this information 

v0.2.2-**8**-g7ca2f70

where 8 indicates the number of commits after the tag has been created.

**Comment by notpeelz** [comment]
I'll be adding this in the next version (2.1.0)

**Comment by PhilippPaetzold** [comment]
Great, I really appreciate this.
