### ISSUE TITLE
error CS0101 and error CS0579

### ISSUE THREAD

**Issue by PhilippPaetzold** [notpeelz/VersionInfoGenerator#4]
With the latest Visual Studio Community 2022 (64-Bit) Update to Version 17.3.4 I get the following erros when building my solution:

```
1>D:\_repos\test\WpfTestLibrary\VersionInfoGenerator\VersionInfoGenerator.VersionInfoGenerator\WpfTestLibrary.VersionInfo.cs(8,27,8,38): error CS0101: Der Namespace "WpfTestLibrary" enthält bereits eine Definition für "VersionInfo".
1>D:\_repos\test\WpfTestLibrary\VersionInfoGenerator\VersionInfoGenerator.VersionInfoGenerator\WpfTestLibrary.VersionInfo.cs(6,6,6,19): error CS0579: Doppeltes Attribut "GeneratedCode".
1>D:\_repos\test\WpfTestLibrary\VersionInfoGenerator\VersionInfoGenerator.VersionInfoGenerator\WpfTestLibrary.VersionInfo.cs(7,6,7,23): error CS0579: Doppeltes Attribut "CompilerGenerated".
``` 

The problem can be reproduced with the following minimal project:

[test.zip](https://github.com/notpeelz/VersionInfoGenerator/files/9638950/test.zip)

I have manually cleaned obj/bin-folders and did a rebuild and also tried the dotnet command line tools without success. When removing the line
```xml
<PackageReference Include="VersionInfoGenerator" Version="2.1.5" PrivateAssets="all" />
``` 

from WpfTestLibrary.csproj the test-app compiles and executes fine.

**Comment by notpeelz** [comment]
Can you check if downgrading to 2.1.3 fixes the issue?

**Comment by PhilippPaetzold** [comment]
Yes that fixed the issue. I can compile the project just fine. Thank you.

**Comment by notpeelz** [comment]
Thanks for confirming. I'll push a fix soon.
